# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: -all
#     custom_cell_magics: kql
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
#   kernelspec:
#     display_name: .venv
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Scalable Multi-Output GPs with OILMM
#
# The [multi-output notebook](multioutput.py) introduces the Intrinsic
# Coregionalisation Model (ICM) and the Linear Model of Coregionalisation (LCM),
# which capture cross-output correlations through coregionalisation matrices. Both
# approaches form the full joint covariance over all $n$ inputs and $p$ outputs.
# In the general case (LCM with $Q > 1$ components) this costs
# $\mathcal{O}((np)^3)$; even the single-component ICM, which enjoys Kronecker
# structure, still requires $\mathcal{O}(n^3 + p^3)$. When $p$ is large, both
# become prohibitive.
#
# The **Orthogonal Instantaneous Linear Mixing Model** (OILMM) of
# [Bruinsma et al. (2020)](https://arxiv.org/abs/1911.06287) sidesteps this
# bottleneck. It models the $p$ outputs as linear mixtures of $m \leq p$ latent
# Gaussian processes through a mixing matrix $\mathbf{H}$ whose columns are
# mutually orthogonal. This orthogonality causes the projected observation noise
# to be diagonal, which in turn allows inference to decompose into $m$ independent
# single-output GP problems. The overall cost drops to $\mathcal{O}(n^3 m)$ —
# linear in the number of latent processes and entirely independent of $p$.
#
# This notebook derives the OILMM mathematics step by step, implements a
# five-output example in GPJax, optimises the model parameters via the OILMM
# log marginal likelihood, and shows how the learned mixing matrix recovers
# the latent structure of the data.

# %%
# Enable Float64 for more stable matrix inversions.
from examples.utils import use_mpl_style
from jax import config
import jax.numpy as jnp
import jax.random as jr
from jaxtyping import install_import_hook
import matplotlib as mpl
import matplotlib.pyplot as plt

config.update("jax_enable_x64", True)

with install_import_hook("gpjax", "beartype.beartype"):
    import gpjax as gpx

key = jr.key(42)
use_mpl_style()
cols = mpl.rcParams["axes.prop_cycle"].by_key()["color"]

# %% [markdown]
# ## The linear mixing model
#
# A common formulation for multi-output GPs assumes that the $p$-dimensional
# output vector is generated by linearly mixing $m$ independent latent GPs:
#
# $$
# \mathbf{y}(t) = \mathbf{H}\,\mathbf{x}(t) + \boldsymbol{\varepsilon}(t),
# $$
#
# where
#
# - $\mathbf{x}(t) = \bigl(x_1(t),\ldots,x_m(t)\bigr)^\top$ collects $m$
#   independent latent GPs, each with kernel $k_i$,
# - $\mathbf{H} \in \mathbb{R}^{p \times m}$ is the **mixing matrix** that maps
#   from latent space to output space, and
# - $\boldsymbol{\varepsilon}(t) \sim \mathcal{N}\bigl(\mathbf{0},\,\sigma^2
#   \mathbf{I}_p\bigr)$ is i.i.d. observation noise.
#
# Given $n$ input locations, we stack all observations into a vector
# $\bar{\mathbf{y}} \in \mathbb{R}^{np}$. Its joint covariance is
#
# $$
# \operatorname{cov}[\bar{\mathbf{y}}]
# = (\mathbf{H} \otimes \mathbf{I}_n)\,
#   \operatorname{blkdiag}(\mathbf{K}_1,\ldots,\mathbf{K}_m)\,
#   (\mathbf{H} \otimes \mathbf{I}_n)^\top
# + \sigma^2\,\mathbf{I}_{np},
# $$
#
# where $\mathbf{K}_i$ is the $n \times n$ Gram matrix of the $i$-th latent
# kernel. Inverting this $np \times np$ matrix naively costs
# $\mathcal{O}(n^3 p^3)$, which is impractical when $p$ is even moderately large.

# %% [markdown]
# ## The OILMM parameterisation
#
# OILMM constrains $\mathbf{H}$ to have **orthogonal columns** by writing
#
# $$
# \mathbf{H} = \mathbf{U}\,\mathbf{S}^{1/2},
# $$
#
# where $\mathbf{U} \in \mathbb{R}^{p \times m}$ has orthonormal columns
# ($\mathbf{U}^\top\mathbf{U} = \mathbf{I}_m$) and
# $\mathbf{S} = \operatorname{diag}(s_1,\ldots,s_m)$ with each $s_i > 0$ is a
# positive diagonal scaling matrix.
#
# The corresponding **projection matrix** is the left pseudo-inverse of
# $\mathbf{H}$:
#
# $$
# \mathbf{T} = \mathbf{S}^{-1/2}\,\mathbf{U}^\top
# \qquad\Longrightarrow\qquad
# \mathbf{T}\,\mathbf{H}
# = \mathbf{S}^{-1/2}\,
#   \underbrace{\mathbf{U}^\top\mathbf{U}}_{\mathbf{I}_m}\,
#   \mathbf{S}^{1/2}
# = \mathbf{I}_m.
# $$
#
# Applying $\mathbf{T}$ to the observed outputs projects them into the latent
# space:
#
# $$
# \tilde{\mathbf{y}}(t)
# = \mathbf{T}\,\mathbf{y}(t)
# = \underbrace{\mathbf{T}\,\mathbf{H}}_{\mathbf{I}_m}\,\mathbf{x}(t)
#   + \mathbf{T}\,\boldsymbol{\varepsilon}(t)
# = \mathbf{x}(t) + \tilde{\boldsymbol{\varepsilon}}(t).
# $$

# %% [markdown]
# ## Diagonal projected noise
#
# The crux of OILMM is that the projected noise
# $\tilde{\boldsymbol{\varepsilon}} = \mathbf{T}\,\boldsymbol{\varepsilon}$ has a
# **diagonal** covariance:
#
# $$
# \operatorname{cov}[\tilde{\boldsymbol{\varepsilon}}]
# = \sigma^2\,\mathbf{T}\,\mathbf{T}^\top
# = \sigma^2\,\mathbf{S}^{-1/2}\,
#   \underbrace{\mathbf{U}^\top\mathbf{U}}_{\mathbf{I}_m}\,
#   \mathbf{S}^{-1/2}
# = \sigma^2\,\mathbf{S}^{-1}.
# $$
#
# Because $\mathbf{S}$ is diagonal, the projected noise components are
# independent: the $i$-th latent observation has noise variance $\sigma^2/s_i$.
# This is the result that makes OILMM tractable.
#
# GPJax additionally supports per-latent heterogeneous noise
# $\mathbf{D} = \operatorname{diag}(d_1,\ldots,d_m)$ with each $d_i \geq 0$.
# Including this term, the full projected noise covariance is
#
# $$
# \boldsymbol{\Sigma}_{\mathbf{T}}
# = \sigma^2\,\mathbf{S}^{-1} + \mathbf{D},
# $$
#
# which remains diagonal.

# %% [markdown]
# ## Independent latent inference
#
# Because the projected noise is diagonal, each projected observation
# $\tilde{y}_i(t) = x_i(t) + \tilde{\varepsilon}_i(t)$ constitutes a standard
# **single-output** GP regression problem with known noise variance
# $\sigma^2/s_i + d_i$. We can therefore condition each latent GP independently
# using the standard conjugate formulae.
#
# The cost of conditioning one GP on $n$ observations is $\mathcal{O}(n^3)$
# (dominated by the Cholesky factorisation), so conditioning all $m$ latent GPs
# costs $\mathcal{O}(n^3 m)$. This is dramatically cheaper than the
# $\mathcal{O}(n^3 p^3)$ cost of the general linear mixing model.

# %% [markdown]
# ## Reconstructing predictions in output space
#
# After conditioning, we obtain posterior means $\boldsymbol{\mu}_i$ and
# covariances $\boldsymbol{\Sigma}_i$ for each latent GP at $n_*$ test locations.
# The output-space predictive distribution is recovered by applying the mixing
# matrix:
#
# \begin{align}
# \boldsymbol{\mu}_{\mathbf{y}}
# &= \mathbf{H}\,
#    \begin{pmatrix}\boldsymbol{\mu}_1 \\ \vdots \\
#    \boldsymbol{\mu}_m\end{pmatrix}, \\[6pt]
# \boldsymbol{\Sigma}_{\mathbf{y}}
# &= (\mathbf{H} \otimes \mathbf{I}_{n_*})\,
#    \operatorname{blkdiag}(\boldsymbol{\Sigma}_1,\ldots,
#    \boldsymbol{\Sigma}_m)\,
#    (\mathbf{H} \otimes \mathbf{I}_{n_*})^\top.
# \end{align}
#
# When only marginal variances are needed, the Kronecker product need not be
# formed explicitly. The marginal variance of output $j$ at test point $t$ is
#
# $$
# \operatorname{var}\bigl[y_j(t)\bigr]
# = \sum_{i=1}^{m} H_{ji}^2\,\operatorname{var}\bigl[x_i(t)\bigr],
# $$
#
# which costs only $\mathcal{O}(n_* p\, m)$.

# %% [markdown]
# ## Synthetic dataset
#
# We construct a five-output dataset driven by two latent functions:
#
# - $x_1(t) = \sin(t)$, a smooth oscillation,
# - $x_2(t) = \cos(t/2)$, a slower oscillation.
#
# The observed outputs are linear mixtures
# $\mathbf{y}(t) = \mathbf{H}_{\text{true}}\,\mathbf{x}(t)
# + \boldsymbol{\varepsilon}$ with noise standard deviation $\sigma = 0.2$. We
# set $m = 2$ latent GPs and $p = 5$ outputs.

# %%
N = 100  # Training points
P = 5  # Output dimensions
M = 2  # Latent GPs

X_train = jnp.linspace(0, 10, N).reshape(-1, 1)

# Two latent functions
latent1 = jnp.sin(X_train.squeeze())
latent2 = jnp.cos(0.5 * X_train.squeeze())

# True mixing weights
true_H = jnp.array(
    [
        [1.0, 0.5],
        [0.8, -0.6],
        [-0.9, 0.3],
        [0.4, 1.1],
        [-0.5, -0.8],
    ]
)

# Generate observations: y = H x + ε
latent_values = jnp.column_stack([latent1, latent2])  # [N, 2]
y_clean = latent_values @ true_H.T  # [N, 5]
y_train = y_clean + jr.normal(key, y_clean.shape) * 0.2

train_data = gpx.Dataset(X=X_train, y=y_train)

print(f"Training data: {N} points, {P} outputs, {M} latent sources")

# %% [markdown]
# Each of the five outputs is a different weighted combination of the two
# underlying latent functions. We plot them alongside the noiseless signal.

# %%
fig, axes = plt.subplots(P, 1, figsize=(10, 1.8 * P), sharex=True)

for p in range(P):
    ax = axes[p]
    ax.plot(
        X_train,
        y_train[:, p],
        "o",
        color=cols[p % len(cols)],
        alpha=0.5,
        ms=3,
        label="Observations",
    )
    ax.plot(X_train, y_clean[:, p], "--", color="grey", label="Noiseless signal")
    ax.set_ylabel(f"Output {p + 1}")
    if p == 0:
        ax.legend(loc="upper right", fontsize=7)

axes[-1].set_xlabel(r"$t$")
plt.suptitle(f"{P} Observed Outputs from {M} Latent Sources", fontsize=13)
plt.tight_layout()

# %% [markdown]
# ## Constructing the OILMM
#
# GPJax provides `create_oilmm_from_data`, which initialises the mixing matrix
# using the empirical correlation structure of the outputs. Concretely, it
#
# 1. computes the empirical covariance matrix
#    $\hat{\boldsymbol{\Sigma}} =
#    \tfrac{1}{n}\,\mathbf{Y}_c^\top\mathbf{Y}_c$,
#    where $\mathbf{Y}_c$ is the column-centred observation matrix;
# 2. extracts the top $m$ eigenvectors **and eigenvalues** of
#    $\hat{\boldsymbol{\Sigma}}$;
# 3. sets $\mathbf{U}_{\text{latent}}$ to the eigenvectors, so that after SVD
#    orthogonalisation the columns of $\mathbf{U}$ align with the principal
#    directions of output variation; and
# 4. sets $\mathbf{S}$ to the corresponding eigenvalues (clamped to $10^{-6}$
#    for numerical stability), giving the scaling an informative starting point.
#
# This is analogous to initialising with PCA: the first $m$ principal components
# capture the most variance and provide a sensible starting point for
# $\mathbf{H}$.

# %%
model = gpx.models.create_oilmm_from_data(
    dataset=train_data,
    num_latent_gps=M,
    key=key,
    kernel=gpx.kernels.Matern52(),
)

print(f"Outputs (p): {model.num_outputs}")
print(f"Latent GPs (m): {model.num_latent_gps}")

# %% [markdown]
# ### Enforcing orthogonality via SVD
#
# The `OrthogonalMixingMatrix` stores an unconstrained matrix
# $\mathbf{U}_{\text{latent}} \in \mathbb{R}^{p \times m}$ and projects it onto
# the Stiefel manifold (the set of matrices with orthonormal columns) at each
# forward pass using the SVD:
#
# $$
# \mathbf{U}_{\text{SVD}},\,\_,\,\mathbf{V}^\top
# = \operatorname{SVD}(\mathbf{U}_{\text{latent}}),
# \qquad
# \mathbf{U} = \mathbf{U}_{\text{SVD}}\,\mathbf{V}^\top.
# $$
#
# This ensures $\mathbf{U}^\top\mathbf{U} = \mathbf{I}_m$ exactly, regardless
# of the optimiser's updates to the unconstrained representation. We verify this
# numerically.

# %%
U = model.mixing_matrix.U
UtU = U.T @ U
print("U^T U (should be I_m):")
print(jnp.round(UtU, decimals=6))

# %% [markdown]
# ## Conditioning on observations (before optimisation)
#
# Before optimising any parameters, we condition with the PCA-initialised
# defaults to establish a baseline. Calling `condition_on_observations` executes
# the OILMM inference algorithm:
#
# 1. **Project**: compute
#    $\tilde{\mathbf{Y}} = \mathbf{T}\,\mathbf{Y}^\top$ in
#    $\mathcal{O}(nmp)$.
# 2. **Condition**: for each latent GP $i$, form a single-output dataset from
#    $\tilde{\mathbf{y}}_i$ with noise variance $\sigma^2/s_i + d_i$, then
#    condition using the standard conjugate formulae in $\mathcal{O}(n^3)$.
# 3. **Return**: an `OILMMPosterior` wrapping the $m$ independent posteriors.

# %%
posterior = model.condition_on_observations(train_data)
print(f"Conditioned {model.num_latent_gps} independent latent GPs on {N} points")

# %% [markdown]
# ## Baseline predictions (before optimisation)
#
# We first inspect the model's output-space predictions using the default
# PCA-initialised parameters. This serves as a baseline against which we can
# later compare the optimised model.

# %%
N_test = 200
X_test = jnp.linspace(0, 10, N_test).reshape(-1, 1)

pre_pred = posterior.predict(X_test, return_full_cov=False)
pre_opt_mean = pre_pred.mean.reshape(N_test, P)
pre_opt_std = jnp.sqrt(jnp.diag(pre_pred.covariance())).reshape(N_test, P)
pre_obs_noise_var = (
    model.mixing_matrix.obs_noise_variance.value
    + model.mixing_matrix.H_squared @ model.mixing_matrix.latent_noise_variance.value
)
pre_obs_std = jnp.sqrt(pre_opt_std**2 + pre_obs_noise_var[None, :])

fig, axes = plt.subplots(P, 1, figsize=(10, 1.8 * P), sharex=True)

for p in range(P):
    ax = axes[p]
    ax.scatter(
        X_train,
        y_train[:, p],
        alpha=0.4,
        s=15,
        color=cols[p % len(cols)],
        label="Training data",
    )
    ax.plot(
        X_train, y_clean[:, p], "--", color="grey", alpha=0.6, label="Noiseless signal"
    )
    ax.plot(
        X_test,
        pre_opt_mean[:, p],
        color=cols[p % len(cols)],
        linewidth=2,
        label="Predictive mean",
    )
    ax.fill_between(
        X_test.squeeze(),
        pre_opt_mean[:, p] - 2 * pre_opt_std[:, p],
        pre_opt_mean[:, p] + 2 * pre_opt_std[:, p],
        alpha=0.2,
        color=cols[p % len(cols)],
        label="95% credible interval",
    )
    ax.set_ylabel(f"Output {p + 1}")
    if p == 0:
        ax.legend(loc="upper right", fontsize=7)

axes[-1].set_xlabel(r"$t$")
plt.suptitle("Before Optimisation", fontsize=13)
plt.tight_layout()

# %% [markdown]
# ## OILMM log marginal likelihood
#
# To move beyond the PCA-initialised defaults, we optimise the model parameters
# by maximising the OILMM log marginal likelihood. Proposition 9 of
# Bruinsma et al. (2020) gives the exact expression:
#
# $$
# \log p(\mathbf{Y})
# = \underbrace{-\tfrac{n}{2}\log|\mathbf{S}|}_{\text{scaling penalty}}
# \;\underbrace{-\tfrac{n(p-m)}{2}\log(2\pi\sigma^2)}_{\text{residual noise}}
# \;\underbrace{-\tfrac{1}{2\sigma^2}\bigl\|(\mathbf{I}_p -
#   \mathbf{U}\mathbf{U}^\top)\mathbf{Y}^\top\bigr\|_F^2}_{\text{projection
#   residual}}
# \;+\;\sum_{i=1}^{m}
#   \underbrace{\log\mathcal{N}\bigl(\tilde{\mathbf{y}}_i \mid \mathbf{0},\,
#   \mathbf{K}_i + (\sigma^2/s_i + d_i)\mathbf{I}_n\bigr)}_{\text{latent GP
#   marginal likelihood}}.
# $$
#
# The first three terms are **correction factors** that account for the
# deterministic projection from output space to latent space:
#
# - **Scaling penalty**: penalises very large or small $s_i$ values, preventing
#   the model from trivially inflating the likelihood by rescaling.
# - **Residual noise**: the log-probability of the $(p - m)$ directions
#   orthogonal to $\mathbf{U}$, which are explained purely by observation noise.
# - **Projection residual**: the squared Frobenius norm of the data component
#   that lies outside the column space of $\mathbf{U}$, divided by $\sigma^2$.
#
# The final summation is simply the sum of $m$ standard single-output GP log
# marginal likelihoods, each evaluated on the projected data.
#
# GPJax implements this in `oilmm_mll(model, data)`, which takes the
# **pre-conditioning** `OILMMModel` (not a posterior) together with the training
# `Dataset`. We negate it for minimisation with `fit_scipy`.

# %%
initial_mll = gpx.models.oilmm_mll(model, train_data)
print(f"Initial OILMM MLL: {initial_mll:.3f}")

# %% [markdown]
# ## Optimisation
#
# We maximise the OILMM log marginal likelihood using L-BFGS via `fit_scipy`.
# The optimiser tunes all `Parameter` leaves: the kernel hyperparameters
# (length-scale, variance) of each latent GP, the unconstrained mixing matrix
# $\mathbf{U}_{\text{latent}}$, the diagonal scaling $\mathbf{S}$, and the noise
# variances ($\sigma^2$ and $\mathbf{D}$).

# %%
opt_model, history = gpx.fit_scipy(
    model=model,
    objective=lambda m, d: -gpx.models.oilmm_mll(m, d),
    train_data=train_data,
    trainable=gpx.parameters.Parameter,
)

opt_mll = gpx.models.oilmm_mll(opt_model, train_data)
print(f"Initial MLL: {initial_mll:.3f}")
print(f"Optimised MLL: {opt_mll:.3f}")
print(f"Improvement: {opt_mll - initial_mll:.3f}")

# %% [markdown]
# ## Post-optimisation predictions
#
# We re-condition the optimised model on the training data, then predict at the
# same test locations. Because the kernel hyperparameters, mixing matrix, and
# noise parameters have all been tuned, we expect substantially tighter credible
# intervals and more accurate predictive means.

# %%
opt_posterior = opt_model.condition_on_observations(train_data)
post_pred = opt_posterior.predict(X_test, return_full_cov=False)
post_opt_mean = post_pred.mean.reshape(N_test, P)
post_opt_std = jnp.sqrt(jnp.diag(post_pred.covariance())).reshape(N_test, P)
post_obs_noise_var = (
    opt_model.mixing_matrix.obs_noise_variance.value
    + opt_model.mixing_matrix.H_squared
    @ opt_model.mixing_matrix.latent_noise_variance.value
)
post_obs_std = jnp.sqrt(post_opt_std**2 + post_obs_noise_var[None, :])

# %% [markdown]
# ## Before vs after comparison
#
# We display the baseline (left) and optimised (right) predictions side by side
# for each output. The grey dashed line shows the noiseless ground-truth signal.

# %%
fig, axes = plt.subplots(P, 2, figsize=(14, 1.8 * P), sharex=True)

for p in range(P):
    col = cols[p % len(cols)]

    for j, (mean, std, title) in enumerate(
        [
            (pre_opt_mean, pre_opt_std, "Before Optimisation"),
            (post_opt_mean, post_opt_std, "After Optimisation"),
        ]
    ):
        ax = axes[p, j]
        ax.scatter(
            X_train,
            y_train[:, p],
            alpha=0.3,
            s=10,
            color=col,
        )
        ax.plot(X_train, y_clean[:, p], "--", color="grey", alpha=0.6)
        ax.plot(X_test, mean[:, p], color=col, linewidth=2)
        ax.fill_between(
            X_test.squeeze(),
            mean[:, p] - 2 * std[:, p],
            mean[:, p] + 2 * std[:, p],
            alpha=0.2,
            color=col,
        )
        ax.set_ylabel(f"Output {p + 1}")
        if p == 0:
            ax.set_title(title, fontsize=11)

axes[-1, 0].set_xlabel(r"$t$")
axes[-1, 1].set_xlabel(r"$t$")
plt.suptitle("OILMM Predictions: Default Parameters vs Optimised", fontsize=13, y=1.01)
plt.tight_layout()

# %% [markdown]
# ## Predictive intervals with observation noise
#
# The previous figure shows uncertainty over the latent noise-free function
# $\mathbf{f}(t) = \mathbf{H}\mathbf{x}(t)$. To visualise uncertainty over
# observed outputs $\mathbf{y}(t)$, we add output-space noise:
#
# $$
# \operatorname{var}[y_j(t)] = \operatorname{var}[f_j(t)]
# + \sigma^2 + \sum_{i=1}^m H_{ji}^2 d_i.
# $$
#
# The wider band below is the 95% predictive interval for noisy observations,
# while the narrower band is the latent-function interval.

# %%
fig, axes = plt.subplots(P, 2, figsize=(14, 1.8 * P), sharex=True)

for p in range(P):
    col = cols[p % len(cols)]

    for j, (mean, func_std, obs_std, title) in enumerate(
        [
            (pre_opt_mean, pre_opt_std, pre_obs_std, "Before Optimisation"),
            (post_opt_mean, post_opt_std, post_obs_std, "After Optimisation"),
        ]
    ):
        ax = axes[p, j]
        ax.scatter(
            X_train,
            y_train[:, p],
            alpha=0.3,
            s=10,
            color=col,
        )
        ax.plot(X_train, y_clean[:, p], "--", color="grey", alpha=0.6)
        ax.plot(X_test, mean[:, p], color=col, linewidth=2)
        ax.fill_between(
            X_test.squeeze(),
            mean[:, p] - 2 * obs_std[:, p],
            mean[:, p] + 2 * obs_std[:, p],
            alpha=0.14,
            color=col,
            label="95% interval (with noise)",
        )
        ax.fill_between(
            X_test.squeeze(),
            mean[:, p] - 2 * func_std[:, p],
            mean[:, p] + 2 * func_std[:, p],
            alpha=0.26,
            color=col,
            label="95% interval (latent f)",
        )
        ax.set_ylabel(f"Output {p + 1}")
        if p == 0:
            ax.set_title(title, fontsize=11)
        if p == 0 and j == 1:
            ax.legend(loc="upper right", fontsize=7)

axes[-1, 0].set_xlabel(r"$t$")
axes[-1, 1].set_xlabel(r"$t$")
plt.suptitle(
    "OILMM Predictive Intervals: Latent Function vs Noisy Observations",
    fontsize=13,
    y=1.01,
)
plt.tight_layout()

# %% [markdown]
# ## Learned parameters
#
# We now inspect what the optimiser has learned. The mixing matrix $\mathbf{H}$
# should approximate the true mixing weights (up to a rotation/sign ambiguity
# inherent to the latent decomposition). We also examine the scaling values
# $\mathbf{S}$, the observation noise $\sigma^2$, the per-latent noise
# $\mathbf{D}$, and the kernel hyperparameters.

# %%
# Learned mixing matrix H
H_learned = opt_model.mixing_matrix.H

fig, ax = plt.subplots(figsize=(4, 5))
im = ax.imshow(
    H_learned,
    cmap="RdBu_r",
    vmin=-jnp.max(jnp.abs(H_learned)),
    vmax=jnp.max(jnp.abs(H_learned)),
    aspect="auto",
)
for row in range(P):
    for col_idx in range(M):
        ax.text(
            col_idx,
            row,
            f"{H_learned[row, col_idx]:.2f}",
            ha="center",
            va="center",
            fontsize=10,
        )
ax.set_xticks(range(M))
ax.set_xticklabels([f"Latent {i + 1}" for i in range(M)])
ax.set_yticks(range(P))
ax.set_yticklabels([f"Output {i + 1}" for i in range(P)])
ax.set_title(r"Learned $\mathbf{H}$")
fig.colorbar(im, ax=ax, shrink=0.7)

# %%
# Scalar parameters
S_vals = opt_model.mixing_matrix.S.value
sigma2 = opt_model.mixing_matrix.obs_noise_variance.value
D_vals = opt_model.mixing_matrix.latent_noise_variance.value

print("Scaling S:")
for i in range(M):
    print(f"  s_{i + 1} = {S_vals[i]:.4f}")
print(f"\nObservation noise sigma^2 = {sigma2:.6f}")
print("\nPer-latent noise D:")
for i in range(M):
    print(f"  d_{i + 1} = {D_vals[i]:.6f}")

print("\nPer-latent kernel hyperparameters:")
for i, prior in enumerate(opt_model.latent_priors):
    k = prior.kernel
    ls = k.lengthscale.value
    var = k.variance.value
    print(f"  Latent GP {i + 1}: lengthscale = {ls:.4f}, variance = {var:.4f}")

# %% [markdown]
# ## Latent space after optimisation
#
# The decomposition into independent single-output problems is the heart of
# OILMM. We plot each latent GP's projected training data
# $\tilde{\mathbf{y}}_i$ alongside its posterior predictive distribution. These
# $m$ panels are completely independent — each latent GP knows nothing about the
# others.
#
# Note that the latent functions are identified only up to a sign/scale ambiguity:
# flipping the sign of a column of $\mathbf{U}$ and the corresponding latent GP
# leaves the output-space predictions unchanged.

# %%
fig, axes = plt.subplots(1, M, figsize=(5 * M, 3), sharey=False)

for i in range(M):
    ax = axes[i]

    # Projected training observations for this latent GP
    lat_y = opt_posterior.latent_datasets[i].y.squeeze()
    ax.plot(X_train, lat_y, "o", color=cols[i], alpha=0.4, ms=3, label="Projected data")

    # Latent posterior prediction
    lat_pred = opt_posterior.latent_posteriors[i].predict(
        X_test, train_data=opt_posterior.latent_datasets[i]
    )
    lat_mean = lat_pred.mean
    lat_std = jnp.sqrt(jnp.diag(lat_pred.covariance()))

    ax.plot(X_test, lat_mean, color=cols[i], linewidth=2, label="Posterior mean")
    ax.fill_between(
        X_test.squeeze(),
        lat_mean - 2 * lat_std,
        lat_mean + 2 * lat_std,
        color=cols[i],
        alpha=0.2,
        label="95% credible interval",
    )
    ax.set_xlabel(r"$t$")
    ax.set_title(f"Latent GP {i + 1}")
    ax.legend(loc="best", fontsize=7)

plt.tight_layout()

# %% [markdown]
# Each latent GP has learned a smooth function that explains the projected
# observations. The credible intervals are narrow where data is dense and widen
# towards the boundaries. Crucially, these $m$ regression problems were solved
# independently, with total cost $\mathcal{O}(n^3 m)$.

# %% [markdown]
# ## Heterogeneous kernels
#
# By default, passing a single kernel to `OILMMModel` deep-copies it $m$ times
# so that each latent GP has **independent** hyperparameters. If the latent
# processes operate at fundamentally different characteristic scales, you can go
# further and assign entirely different kernel families:
#
# ```python
# model = gpx.models.create_oilmm(
#     num_outputs=5, num_latent_gps=2, key=key,
#     kernel=[gpx.kernels.RBF(), gpx.kernels.Matern52()],
# )
# ```
#
# The first latent GP would then use an infinitely differentiable RBF kernel
# while the second uses the rougher Matern-5/2. This is analogous to the
# advantage of LCM over ICM in the multi-output setting, where different
# components can capture different spectral characteristics.

# %% [markdown]
# ## Computational complexity
#
# The table below summarises the cost of each phase of OILMM inference for $n$
# training points, $p$ outputs, and $m$ latent GPs.
#
# | Phase | Operation | Cost |
# |-------|-----------|------|
# | Projection | $\tilde{\mathbf{Y}} = \mathbf{T}\,\mathbf{Y}^\top$ | $\mathcal{O}(nmp)$ |
# | Conditioning | $m$ independent Cholesky factorisations | $\mathcal{O}(n^3 m)$ |
# | Prediction (mean) | $\boldsymbol{\mu}_{\mathbf{y}} = \mathbf{H}\,\boldsymbol{\mu}$ | $\mathcal{O}(n_* m p)$ |
# | Prediction (marginal variance) | $\mathbf{H}^{\circ 2}\,\mathbf{v}$ | $\mathcal{O}(n_* m p)$ |
#
# The dominant cost is $\mathcal{O}(n^3 m)$, which is **linear** in $m$ and
# **independent** of $p$. For comparison:
#
# - A general multi-output GP (e.g. LCM with $Q > 1$) costs
#   $\mathcal{O}(n^3 p^3)$.
# - ICM with Kronecker structure costs $\mathcal{O}(n^3 + p^3)$.
# - OILMM costs $\mathcal{O}(n^3 m)$.
#
# With $p = 5$ and $m = 2$ the ratio is $p^3/m = 62.5$, so OILMM offers a
# substantial speed-up over the dense multi-output approach — and the advantage
# grows rapidly as $p$ increases.

# %%
print(f"Standard multi-output cost: O(n^3 p^3) = O({N}^3 x {P}^3)")
print(f"OILMM cost:                O(n^3 m)  = O({N}^3 x {M})")
print(f"Theoretical speedup:       p^3 / m   = {P**3 / M:.1f}x")

# %% [markdown]
# ## System configuration

# %%
# %reload_ext watermark
# %watermark -n -u -v -iv -w -a 'Thomas Pinder'
